<HTML>
	<body>
		<table bordercolor='3399ff' border='1' cellpadding='0' cellspacing='0'>
			<tr><td>
			<table>
				<tr><td colspan='3'><table width='100%' bgcolor="3399ff" cellpadding='0' cellspacing='0'><tr><th>&nbsp;&nbsp;Current conditions at $display_location_city$,$display_location_state$ $display_location_zip$&nbsp;&nbsp;</th><td><img src='http://icons-ecast.wxug.com/i/c/a/clear.gif'/></td></tr></table></td></tr>
				<tr><td colspan='3' bgcolor="FFFFCC">$observation_time$</td></tr>
				<tr><th bgcolor="FFFFCC" align='left'>Temperature:</th><td bgcolor="FFFFCC" align='left'>88 F</td><td bgcolor="FFFFCC" align='left'>31 C</td></tr>
				<tr><th bgcolor="FFFFCC" align='left'>Humidity:</th><td bgcolor="FFFFCC" align='left' colspan='2'>66%</td></tr>
				<tr><th bgcolor="FFFFCC" align='left'>Wind:</th><td bgcolor="FFFFCC" align='left' colspan='2'>From the East at 6 MPH</td></tr>
				<tr><th bgcolor="FFFFCC" align='left'>Barometric Pressure:</th><td bgcolor="FFFFCC" align='left' colspan='2'>30.10 in (1019 mb)</td></tr>
				<tr><th bgcolor="FFFFCC" align='left'>DewPoint:</th><td bgcolor="FFFFCC" align='left' colspan='2'>75 F (24 C)</td></tr>
				<tr><th bgcolor="FFFFCC" align='left'>Heat Index:</th><td bgcolor="FFFFCC" align='left' colspan='2'>98 F (36 C)</td></tr>
				<tr><th bgcolor="FFFFCC" align='left'>Wind Chill:</th><td bgcolor="FFFFCC" align='left' colspan='2'>NA</td></tr>
				<tr><th bgcolor="FFFFCC" align='left'>Visibility:</th><td bgcolor="FFFFCC" align='left' colspan='2'>10.0 mi (16.1 km)</td></tr>
			</table>
			</td></tr>
		</table>
	</body>
</HTML>