<HTML>
	<body>
		<table bordercolor='3399ff' border='1' cellpadding='0' cellspacing='0'>
			<tr><td>
			<table>
				<tr><td colspan='3'><table width='100%' bgcolor="3399ff" cellpadding='0' cellspacing='0'><tr><th>&nbsp;&nbsp;Current conditions at $display_location_city$,$display_location_state$ $display_location_zip$&nbsp;&nbsp;</th><td><img src='http://icons-ecast.wxug.com/i/c/a/clear.gif'/></td></tr></table></td></tr>
				<tr><td colspan='3' bgcolor="FFFFCC">$observation_time$</td></tr>
				<tr><th bgcolor="FFFFCC" align='left'>Temperature:</th><td bgcolor="FFFFCC" align='left'>$temp_f$ F</td><td bgcolor="FFFFCC" align='left'>$temp_c$ C</td></tr>
				<tr><th bgcolor="FFFFCC" align='left'>Humidity:</th><td bgcolor="FFFFCC" align='left' colspan='2'>$relative_humidity$</td></tr>
				<tr><th bgcolor="FFFFCC" align='left'>Wind:</th><td bgcolor="FFFFCC" align='left' colspan='2'>$wind_string$</td></tr>
				<tr><th bgcolor="FFFFCC" align='left'>Barometric Pressure:</th><td bgcolor="FFFFCC" align='left' colspan='2'>$pressure_string$</td></tr>
				<tr><th bgcolor="FFFFCC" align='left'>DewPoint:</th><td bgcolor="FFFFCC" align='left' colspan='2'>$dewpoint_string$</td></tr>
				<tr><th bgcolor="FFFFCC" align='left'>Heat Index:</th><td bgcolor="FFFFCC" align='left' colspan='2'>$heat_index_string$</td></tr>
				<tr><th bgcolor="FFFFCC" align='left'>Wind Chill:</th><td bgcolor="FFFFCC" align='left' >$windchill_f$ F</td><td bgcolor="FFFFCC" align='left' >$windchill_c$ F</td></tr>
				<tr><th bgcolor="FFFFCC" align='left'>Visibility:</th><td bgcolor="FFFFCC" align='left' colspan='2'>$visibility_mi$ mi ($visibility_km$ km)</td></tr>
			</table>
			</td></tr>
		</table>
	</body>
</HTML>