<div style="background-color: #3399ff; width: 250">
	<div style="background-color: #3399ff;font-weight: bold">&nbsp;&nbsp;Current conditions at $display_location_city$,$display_location_state$ $display_location_zip$&nbsp;&nbsp;<img src='http://icons-ecast.wxug.com/i/c/a/clear.gif'/></div>
	<div style="background-color: #FFFFCC;">$observation_time$</div>
	<div style="background-color: #FFFFCC;">Temperature:&nbsp;&nbsp;$temp_f$ F&nbsp;&nbsp;$temp_c$ C</div>
	<div style="background-color: #FFFFCC;">&nbsp;</div>
</div>